<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>879e1c83-ae8d-47a2-9f56-453dde2926ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>223d19f3-f893-4d87-a81a-e2541c922056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6ca47e9e-f7de-4206-88da-feeaa5bfefbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a042fc1-9a9d-4ea2-968b-673b5b5d67f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>711f557d-5e0d-4af8-9290-a4862408bfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine igx-input-group__input ng-invalid</value>
      <webElementGuid>1362bd9f-8de2-4382-a606-2e9b546e0782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-0&quot;)/div[@class=&quot;igx-input-group__bundle&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;ng-untouched ng-pristine igx-input-group__input ng-invalid&quot;]</value>
      <webElementGuid>b8e458e7-b823-46d3-ac3c-413f27b34c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Email']</value>
      <webElementGuid>44ee3e74-417e-4ba2-a030-4149f11fb201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-0']/div/div/input</value>
      <webElementGuid>6540151e-8b5e-495d-a6f1-9b772525cc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9daf35de-e060-4d05-9f8d-ca768b43203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Email' and @type = 'text']</value>
      <webElementGuid>0cc7e583-e05e-489e-a489-916eaff4c140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
